name: Android CI

on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    # Step 4: Add FCM configuration
    - name: Setup Firebase Credentials
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        BACKEND_URL: ${{ secrets.BACKEND_URL }}
      run: |
        sed -i 's|<string name="app_base_url" translatable="false">https://ntfy.sh</string>|<string name="app_base_url" translatable="false">${{ secrets.BACKEND_URL }}</string>|' app/src/main/res/values/values.xml
        cat app/src/main/res/values/values.xml
        echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assemblePlayRelease
    - name: Upload to Artifacts
      uses: actions/upload-artifact@v4
      with:
         name: ntfy
         path: app/build/outputs/apk/play/release/*.apk
         if-no-files-found: error
